[package]
name = "qmkfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
streaming-iterator = "0.1.9"
tree-sitter = "0.24"
tree-sitter-c = "0.23.2"
